USE MYDB;

INSERT INTO Station(name) VALUES ('A');
INSERT INTO Station(name) VALUES ('B');
INSERT INTO Station(name) VALUES ('C');
INSERT INTO Station(name) VALUES ('D');
INSERT INTO Station(name) VALUES ('E');
INSERT INTO Station(name) VALUES ('F');
INSERT INTO Station(name) VALUES ('G');
INSERT INTO Station(name) VALUES ('H');
INSERT INTO Station(name) VALUES ('I');
INSERT INTO Station(name) VALUES ('J');
INSERT INTO Station(name) VALUES ('K');
INSERT INTO Station(name) VALUES ('L');
INSERT INTO Station(name) VALUES ('M');
INSERT INTO Station(name) VALUES ('N');
INSERT INTO Station(name) VALUES ('O');
INSERT INTO Station(name) VALUES ('P');
INSERT INTO Station(name) VALUES ('Q');
INSERT INTO Station(name) VALUES ('R');
INSERT INTO Station(name) VALUES ('S');
INSERT INTO Station(name) VALUES ('T');
INSERT INTO Station(name) VALUES ('U');
INSERT INTO Station(name) VALUES ('V');
INSERT INTO Station(name) VALUES ('W');
INSERT INTO Station(name) VALUES ('X');
INSERT INTO Station(name) VALUES ('Y');
INSERT INTO Station(name) VALUES ('Z');